hibernate.connection.url=${MYSQL_URL:jdbc:p6spy:mysql://localhost:3306/rpg}
hibernate.connection.driver_class=com.p6spy.engine.spy.P6SpyDriver
hibernate.connection.username=${MYSQL_USER:root}
hibernate.connection.password=${MYSQL_PASSWORD:root}
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=validate